{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
   ],
   "source": [
    "%hide\n",
    "%html\n",
    "<H3  ALIGN=\"CENTER\"><FONT COLOR=\"#030856\">\n",
    "DE models for the spread \n",
    "of grassroots political views\n",
    "</FONT></H3>\n",
    "\n",
    "<H5>\n",
    "    Introduction\n",
    "</H5>\n",
    "\n",
    "\n",
    "Differential equation models for the spread of infectious \n",
    "diseases have been widely extended and adapted to a \n",
    "variety of other application areas.  In this lab we explore a \n",
    "class of similar models for studying the spread of \n",
    "political views.  As with infectious diseases, the overall \n",
    "strategy consists of splitting the entire population into \n",
    "distinct, non-overlapping groups, whose numbers change \n",
    "as a function of time.\n",
    "<P></P>\n",
    "\n",
    "Consider, for example, the problem of modeling a political \n",
    "issue on which there are only two sides.  Let $N$ denote the \n",
    "population of interest and let $I$ represent the number of \n",
    "individuals in \n",
    "the population who support the political idea under \n",
    "consideration.  Then the number who \n",
    "oppose the idea would be $S=N-I$.  This provides a natural \n",
    "framework for adapting an SIS (Susceptible-Infected-Susceptible) \n",
    "type of infectious disease \n",
    "model.\n",
    "<P></P>\n",
    "\n",
    "<TABLE ALIGN=\"CENTER\" WIDTH=\"80%\" BORDER=\"0\"  CELLSPACING=\"0\"  CELLPADDING=\"8\">\n",
    "  <TR VALIGN=\"TOP\">\n",
    "    <TD ALIGN=\"CENTER\">\n",
    "      <IMG SRC=\"./sis_picture.png\" width=\"400\">\n",
    "      </IMG>\n",
    "    </TD>\n",
    "  </TR>\n",
    "</TABLE>\n",
    "\n",
    "\n",
    "As seen in the compartmental sketch, the only difference \n",
    "between the disease and the political ideas model is \n",
    "in how we interpret the contents of each compartment.  \n",
    "However, the options get more interesting, and diverse, \n",
    "if we consider models with 3 or more compartments.  \n",
    "For instance, the compartmental sketch below shows an \n",
    "SIRS (Susceptible-Infected-Recovered-Susceptible)\n",
    "schematic for diseases and for political ideas.  \n",
    "<P></P>\n",
    "\n",
    "<TABLE ALIGN=\"CENTER\" WIDTH=\"80%\" BORDER=\"0\"  CELLSPACING=\"0\"  CELLPADDING=\"8\">\n",
    "  <TR VALIGN=\"TOP\">\n",
    "    <TD ALIGN=\"CENTER\">\n",
    "      <IMG SRC=\"./sirs_picture.png\" width=\"500\">\n",
    "      </IMG>\n",
    "    </TD>\n",
    "  </TR>\n",
    "</TABLE>\n",
    "\n",
    "Unlike the infectious disease situation, in the case of \n",
    "political ideas, members of any group \n",
    "can directly move into any other group.  Thus, the model \n",
    "terms must be modified to account for these additional \n",
    "possibilities."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
   ],
   "source": [
    "%hide\n",
    "%html\n",
    "\n",
    "<H5>\n",
    "    Lab project\n",
    "</H5>\n",
    "\n",
    "We will develop an SIS and SIR type of model for the spread \n",
    "of political ideas.  This will involve model development, \n",
    "analysis, and parameter estimation.  To help us think \n",
    "concretely through the details of model development, we \n",
    "will work with historical data from past political events.  \n",
    "The figure below shows a 5-year history of U.S. public opinion \n",
    "about the U.S. war against Iraq, compiled by the Pew Research \n",
    "Center.\n",
    "<P></P>\n",
    "\n",
    "<TABLE ALIGN=\"CENTER\" WIDTH=\"80%\" BORDER=\"0\"  CELLSPACING=\"0\"  CELLPADDING=\"8\">\n",
    "  <TR VALIGN=\"TOP\">\n",
    "    <TD ALIGN=\"CENTER\">\n",
    "      <IMG SRC=\"./pew_iraqwar.png\"  width=\"700\">\n",
    "      </IMG>\n",
    "    </TD>\n",
    "  </TR>\n",
    "</TABLE>\n",
    "\n",
    "\n",
    "Although the results are shown in the form of a graph, \n",
    "the details are sufficient to estimate approximate values \n",
    "for the parameters, and to fit approximate \n",
    "models to the data.  We will study two models for \n",
    "simulating these data.\n",
    "<P>&nbsp;</P>\n",
    "\n",
    "\n",
    "<OL>\n",
    "    <LI><B>The SIS model:</B> \n",
    "From the epidemiology literature, this model has the form\n",
    "\\[\n",
    "  S^\\prime = -\\beta \\frac{S I}{N} + \\gamma I  \\\\\n",
    "  I^\\prime = \\beta \\frac{S I}{N} - \\gamma I \n",
    "\\]\n",
    "where $S$ and $I$, respectively, denote the number of \n",
    "susceptibles and infectives in a population of constant size $N$, and \n",
    "the rest of the quantities are parameters.  In adapting this \n",
    "model to political ideas/opinion, we would need to associate \n",
    "$S$ and $I$ with the number of people on either side of a \n",
    "political position.  This model doesn't permit more than two \n",
    "sides for the political position.  We will do our best to fit \n",
    "it to the Iraq war data.  To keep things simple, let $N=100$.  \n",
    "Then $S$, $I$, will directly correspond to percentages \n",
    "of the population.  Here are some items to explore and address </LI>\n",
    "<SUP>&nbsp;</SUP>\n",
    "<UL>\n",
    "    <LI>The SIS model admits non-zero, stable equilibrium \n",
    "solution(s).  Why does that suggest it may be \n",
    "suitable to simulate the Pew data (if we focus on two variables)? </LI>\n",
    "\n",
    "    <LI>Make<SUP>&nbsp;</SUP>suitable choices for the two variables, e.g., by \n",
    "ignoring one variable or combining it with one of the others. </LI>\n",
    "\n",
    "    <LI>Using<SUP>&nbsp;</SUP>the Pew data, estimate the values of the \n",
    "parameters in the model.  Use data from the graphs, together \n",
    "with your understanding of equilibrium solutions and stability \n",
    "to get the best parameter values.  Compute solutions (using Sage \n",
    "or other methods) and show how well your model works. </LI>\n",
    "</UL>\n",
    "\n",
    "<P>&nbsp;</P>\n",
    "\n",
    "\n",
    "    <LI><B>The SIZS model:</B> \n",
    "This is an extension of the \n",
    "SIR model from epidemiology.  The key difference is that it \n",
    "allows members of any group to directly move into any \n",
    "other group.  The model has the form\n",
    "\\[\n",
    "  S^\\prime = -\\beta_i \\frac{(S+Z) I}{N} - \\beta_z \\frac{(S+I) Z}{N} \n",
    "        + \\gamma_i I + \\gamma_z Z  \\\\\n",
    "  I^\\prime =  \\beta_i \\frac{(S+Z) I}{N} - \\gamma_i I \\\\\n",
    "  Z^\\prime =  \\beta_z \\frac{(S+I) Z}{N}  - \\gamma_z Z\n",
    "\\]\n",
    "In this model, the variables would have the following \n",
    "interpretation:  <BR></BR>\n",
    "    $S(t) =$ number of susceptible people at time t \n",
    "(e.g., no opinion on the Iraq war) <BR></BR>\n",
    "    $I(t) = $ number of people \"infected\" with the idea  <BR></BR>\n",
    "    $Z(t) = $ number of people opposed to the idea $I(t)$ above  <BR></BR>\n",
    "\n",
    "Here are the tasks to consider with this model\n",
    " </LI>\n",
    "<SUP>&nbsp;</SUP>\n",
    "<UL>\n",
    "    <LI>Make suitable choices for the variables. </LI>\n",
    "    <LI>Using the Pew data, estimate the values of the \n",
    "parameters in the model.  Think about equilibrium \n",
    "solutions and stability to help in this task. </LI>\n",
    "    <LI>Here is one strategy that works, though there may \n",
    "be others that work even better.  The segment below is \n",
    "reproduced from my rough notes, so use it at your own risk! <BR></BR>\n",
    "There are 4 parameters in this model.  \n",
    "Suppose we know the long-term (steady-state) values \n",
    "of S, I, Z.  In other words, we know $S(\\infty)$, $I(\\infty)$, \n",
    "and $Z(\\infty)$.  Then, we can compute the following two ratios:\n",
    "<BR></BR>\n",
    "        $\\gamma_i/\\beta_i = (S + Z) / N$,   \n",
    "        $\\gamma_z/\\beta_z = (S + I) / N$\n",
    "<BR></BR>\n",
    "Next, suppose we can find a way to estimate \n",
    "$I^\\prime(0)$ and $Z^\\prime(0)$, together with the values \n",
    "$S(0), I(0), Z(0)$.  From the model ODEs we get\n",
    "<BR></BR>\n",
    "        $\\gamma_i = \\beta_i [S(0)+Z(0)] / N  - I^\\prime(0)/I(0)$, \n",
    "        $\\gamma_z = \\beta_z [S(0)+I(0)] / N  - Z^\\prime(0)/Z(0)$\n",
    "<BR></BR>\n",
    "Then $\\gamma_i, \\gamma_z$ are known in terms of \n",
    "$\\beta_i, \\beta_z$ respectively.  These can be plugged into the \n",
    "previous $\\gamma_i/\\beta_i$, $\\gamma_z/\\beta_z$ ratios.\n",
    " </LI>\n",
    "\n",
    "    <LI>Compute solutions (using Sage \n",
    "or other methods) and show how well your model works. </LI>\n",
    "\n",
    "</UL>\n",
    "\n",
    "</OL>\n",
    "<P>&nbsp;</P>\n",
    "Shown below is sample sage code to solve a system of 3 ODEs \n",
    "and plot each component of the solution on a common axis."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
   ],
   "source": [
    "# Example showing num soln of the SIR diff eqn model\n",
    "# Systems is: S'= - b*S*I; I' = b*S*I -g*I; R'= g*I\n",
    "\n",
    "s, i, r, t = var('s i r t')\n",
    "b = 5e-6\n",
    "g = 1/2\n",
    "s0 = 1e6\n",
    "i0 = 5\n",
    "r0 = 0\n",
    "de1 = - b*s*i\n",
    "de2 = b*s*i - g*i\n",
    "de3 = g*i\n",
    "P = desolve_system_rk4 ([de1, de2, de3], [s, i, r], ics=[0, s0, i0, r0], ivar=t, end_points=[0,15] )\n",
    "Q = [ [i,j] for i, j, k, l in P]\n",
    "P1 = line(Q)\n",
    "Q = [ [i,k] for i, j, k, l in P]\n",
    "P2 = line(Q, color='green')\n",
    "Q = [ [i,l] for i, j, k, l in P]\n",
    "P3 = line(Q, color='red')\n",
    "show(P1+P2+P3)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "SageMath (stable)",
   "name": "sagemath"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}